package:
  name: gocat
  version: 0.2.0
  description: 21st century, multi-purpose relay from source to destination
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - go
      - git

pipeline:
  - name: Build Go application
    runs: |
      CGO_ENABLED=0 go build -o "${{targets.destdir}}/bin/gocat" .
